products = [
    {
        "_id": "1",
        "name": "Running Shoes",
        "image": "/images/running-shoes.jpg",
        "description": "Comfortable running shoes for all types of runners.",
        "brand": "Nike",
        "category": "Running",
        "price": 89.99,
        "countInStock": 10,
        "rating": 4.5,
        "numReviews": 8,
    },
    {
        "_id": "2",
        "name": "Basketball Sneakers",
        "image": "/images/basketball-sneakers.jpg",
        "description": "High-performance basketball sneakers for agility and support.",
        "brand": "Adidas",
        "category": "Basketball",
        "price": 129.99,
        "countInStock": 15,
        "rating": 4.0,
        "numReviews": 12,
    },
    {
        "_id": "3",
        "name": "Adidas Ultra Boost",
        "image": "/images/adidas-ultra-boost.jpg",
        "description": "Premium cushioned running shoes for maximum comfort.",
        "brand": "Adidas",
        "category": "Running",
        "price": 159.99,
        "countInStock": 8,
        "rating": 4.7,
        "numReviews": 15,
    },
    {
        "_id": "4",
        "name": "Puma Ignite XT",
        "image": "/images/puma-ignite-xt.jpg",
        "description": "Versatile and dynamic training shoes for various workouts.",
        "brand": "Puma",
        "category": "Training",
        "price": 79.99,
        "countInStock": 12,
        "rating": 4.2,
        "numReviews": 10,
    },
    {
        "_id": "5",
        "name": "Nike Air Max",
        "image": "/images/nike-air-max.jpg",
        "description": "Iconic Nike sneakers with visible Air Max cushioning.",
        "brand": "Nike",
        "category": "Athletic",
        "price": 119.99,
        "countInStock": 18,
        "rating": 4.9,
        "numReviews": 25,
    },
    {
        "_id": "6",
        "name": "Converse Chuck Taylor All Star",
        "image": "/images/converse-chuck-taylor.jpg",
        "description": "Classic and timeless high-top sneakers from Converse.",
        "brand": "Converse",
        "category": "Casual",
        "price": 54.99,
        "countInStock": 25,
        "rating": 4.6,
        "numReviews": 22,
    },
    {
        "_id": "7",
        "name": "Veja V-10 Sneakers",
        "image": "/images/veja-v10.jpg",
        "description": "Sustainable and stylish sneakers from Veja.",
        "brand": "Veja",
        "category": "Fashion",
        "price": 99.99,
        "countInStock": 14,
        "rating": 4.4,
        "numReviews": 16,
    },
    {
        "_id": "8",
        "name": "UGG Classic Short Boots",
        "image": "/images/ugg-classic-short.jpg",
        "description": "Cozy and warm short boots from UGG.",
        "brand": "UGG",
        "category": "Winter",
        "price": 129.99,
        "countInStock": 10,
        "rating": 4.3,
        "numReviews": 14,
    },
    {
        "_id": "9",
        "name": "New Balance Fresh Foam",
        "image": "/images/new-balance-fresh-foam.jpg",
        "description": "Lightweight and responsive running shoes from New Balance.",
        "brand": "New Balance",
        "category": "Running",
        "price": 94.99,
        "countInStock": 16,
        "rating": 4.5,
        "numReviews": 20,
    },
]
